### PR TITLE
Add hebrew support

### PR DESCRIPTION
**Pull request by Paveltarno**
Hi!
Iv'e added basic Hebrew support for Duckling, it's still not perfect and can only quack numbers and dates. Some of the tests and rules are commented out but hopefully they will be added later.
Thanks a lot for a great library [= (and an opportunity to experiment with Clojure)

### CODE REVIEW

**Comment by patapizza** [comment]
@Paveltarno Sorry for the delay.

Can you move corpus/_time.clj to corpus/time.clj and comment out the failing tests?

```
(run)
...
:he$core: 226 examples, 66 failed.
...
```

**Comment by patapizza** [comment]
Thanks @Paveltarno !

I'll take care of the suggested changes.

**Comment by FraBle** [comment]
Is there a reason, that I get a lot of "not found" messages when I load the lib?
```
"not found" "שני השמונה עשרה לפברואר"
"not found" "שלישי ה19"
"not found" "הראשון למרץ"
"not found" "ה1 למרץ"
"not found" "השלישי למרץ 2015"
"not found" "ב15 לחודש"
"not found" "ב15 החודש"
"not found" "חמש עשרה לחודש"
"not found" "יום שני, ה18 לפברואר"
"not found" "שני, השמונה עשרה לפברואר"
"not found" "שנה שעברה"
"not found" "יום שלישי הראשון של אוקטובר"
"not found" "@ 3pm"
"not found" "באיזור שלוש בצהריים"
"not found" "בשלוש ורבע בצהריים"
"not found" "3:15 בצהריים"
"not found" "3:20 בצהריים"
"not found" "3:20 צהריים"
"not found" "עשרים אחרי שלוש בצהריים"
"not found" "בשלוש וחצי בערב"
"not found" "שלוש וחצי בצהריים"
"not found" "בשבע וחצי בערב ביום שישי העשרים לספטמבר"
"not found" "לפני שלושה חודשים"
```
It's coming from https://github.com/wit-ai/duckling_old/blob/master/src/duckling/learn.clj#L52

**Comment by FraBle** [comment]
@Paveltarno: could you have a look at this?

**Comment by Paveltarno** [comment]
@FraBle, sorry for the delay, to my best knowledge these bugs weren't there before..
I'll investigate it further, until then, I'll submit a PR with the failing examples commented out

**Comment by Paveltarno** [comment]
@FraBle Iv'e submitted a bug for this issue (#242) and a PR (#243)
However, as clojure duckling is now deprecated I'm not sure if these changes will make it to a release

**Comment by ar7hur** [comment]
@Paveltarno @FraBle we are trying to find a way for Clojure Duckling to continue its active life outside of Wit.ai/Facebook. In the meantime I'll process the PRs asap, please apologize for the slow response.

**Pull request merged**
