### PR TITLE
Irish

### PR DESCRIPTION
**Pull request by jimregan**
There's a lot left to do before I'd want to merge this, but I'm a bit stumped about this:

```
(p/parse :ga$core "aon")
=> ()
(p/play :ga$core "aon")
  ---   2 | temperature | number as temp            | P = -2.5903 | numbers, 1-10
  ---   1 | number    | numbers, 1-10             | P = 0.0000 | 
  aon
```

Any suggestions about what's going wrong?

### CODE REVIEW

**Comment by ar7hur** [comment]
Can you try `(p/parse :ga$core "aon" [:number])`?

**Comment by jimregan** [comment]
Same thing:
```
myproject.core=> (p/parse :ga$core "aon" [:number])
()
```

**Comment by jimregan** [comment]
Sorry, I had '(i?)' where I meant to have '(?i)'

**Comment by ar7hur** [comment]
Sorry for the long delay. I tried it today but I get the following errors. It may be due to recent merges in master. Could you please have a look?

> duckling.core=> (load!)
> "not found" "ten cents"
> "not found" "$10,000"
> "not found" "10K$"
> "not found" "$10k"
> "not found" "USD1.23"
> "not found" "2 dollar and 23 cents"
> "not found" "two dollar 23 cents"
> "not found" "two dollar and 23"
> "not found" "EUR29.99"
> "not found" "nine pounds"
> "not found" "GBP3.01"
> "not found" "GBP 3.01"
> "not found" "3.0 km"
> "not found" "37 céimeanna ceinteagrád"
> "not found" "-10°"
> "not found" "- 10 céimeanna"
> {:pt$core (:phone-number :number :distance :volume :temperature :time :url :email :timezone :unit :amount-of-money :leven-unit :quantity :ordinal :unit-of-duration :cycle :duration), :ko$core (:number), :ru$core (:number :ordinal), :ja$core (:number :temperature :ordinal), :fr$core (:phone-number :number :time :distance :volume :temperature :url :email :timezone :unit :amount-of-money :leven-unit :leven-product :quantity :ordinal :cycle :unit-of-duration :duration), :es$core (:phone-number :number :distance :volume :temperature :time :url :email :timezone :unit :amount-of-money :cycle :unit-of-duration :duration :ordinal), :da$core (:number :time :timezone :ordinal :cycle :unit-of-duration :duration), :zh$core (:number :temperature :time :ordinal :cycle :unit-of-duration :duration), :ar$core (:number :ordinal), :ga$core (:unit :number :amount-of-money :distance :volume :temperature :time), :it$core (:number :time :ordinal :cycle :unit-of-duration :duration), :de$core (:number :time :ordinal :cycle :unit-of-duration :duration :timezone), :uk$core (:number :ordinal), :et$core (:number :ordinal), :en$core (:phone-number :number :distance :volume :temperature :time :url :email :timezone :unit :amount-of-money :leven-unit :quantity :leven-product :ordinal :cycle :unit-of-duration :duration)}
> duckling.core=> (run)
> 
> IllegalArgumentException Don't know how to create ISeq from: java.lang.Character  clojure.lang.RT.seqFrom (RT.java:542)
> :pt$core: 382 examples, 0 failed.
> :ko$core: 85 examples, 0 failed.
> :ru$core: 84 examples, 0 failed.
> :ja$core: 55 examples, 0 failed.
> :fr$core: 486 examples, 0 failed.
> :es$core: 295 examples, 0 failed.
> :da$core: 354 examples, 0 failed.
> :zh$core: 329 examples, 0 failed.
> :ar$core: 31 examples, 0 failed.
> 0 FAIL "ten cents"
>     Expected null
> 1 FAIL "$10,000"
>     Expected D

**Comment by jimregan** [comment]
@ar7hur all but one fixed (that one is disabled until I can figure out what's going wrong), no errors now

**Comment by jimregan** [comment]
ok, all fixed

**Comment by ar7hur** [comment]
Thanks!

**Pull request merged**
