### PR TITLE
add numbers in Portuguese

### PR DESCRIPTION
**Pull request by vstabile**

### CODE REVIEW

**Comment by Francis88** [comment]
Thanks for the pull request. Can I ask you to commit it into the develop branch instead? Thanks

**Comment by l5t** [comment]
Thanks for the pull request. Can I ask you to commit it into the develop branch instead? Thanks

**Comment by vstabile** [comment]
sure

**Comment by l5t** [comment]
Closing this one. Thanks a lot for committing in the develop branch

**Pull request closed without merging**
