### PR TITLE
Added Dutch language

### PR DESCRIPTION
**Pull request by robinvdvleuten**
Hi there,

I've added (with some help of @MichielDeMey) support for Dutch numbers. Still some errors on a couple of formats, but maybe you guys would like to help 😅 

Cheers!

Robin

### CODE REVIEW

**Comment by robinvdvleuten** [comment]
@patapizza easier said than done 😉  somehow I can't get the combined words working, like _driehonderd_ = _300_ (_drie_ = _3_, _honderd_ = _100_). All other languages in the repo only have separated corpus examples (which I have working as well). Any tips to get it further?

**Comment by patapizza** [comment]
@robinvdvleuten Ha yes I think we have the same issue in German. OK so let's comment out the failing examples and merge.

**Comment by robinvdvleuten** [comment]
@patapizza I've commented them out for now

**Comment by patapizza** [comment]
@robinvdvleuten Haartelijk bedankt!

**Comment by robinvdvleuten** [comment]
@patapizza expect some more types in the near future :bowtie:

**Comment by joachimdb** [comment]
Nice, thanks robin! I'd like to help, although I'm still new to Duckling (discovered it just yesterday :) ). What is the general strategy to cope with concatenated words?

**Comment by robinvdvleuten** [comment]
@joachimdb I guess that they should be resolved like separated values. So _vijfduizend_ would resolve first to _1000_ and then to _5_, when duckling will apply the multiplier and gets _5000_. But clojure isn't my core business haha and did a lot of trial and error while running (load!).

**Pull request merged**
