### PR TITLE
RO language

### PR DESCRIPTION
**Pull request by brezuicabogdan**
Added RO langiage with all entities that were already in english. All test pass

### CODE REVIEW

**Comment by brezuicabogdan** [comment]
Hello,

this is my first interaction with both Clojure and duckilngs so I hope I've done a good enough job. I'm open to criticism :)

**Comment by brezuicabogdan** [comment]
That s awkward cause numbers were the first thing I did and all the examples passed. Shure. I ll take a look at it first thing tomorrow morning. Also if there s anything I overlooked please tell me as this is my first experience with Clojure and I m kinda thinking inside the box here. Thanks

**Comment by brezuicabogdan** [comment]
Done.

> duckling.core=> (load! {:languages ["ro"]})
{:ro$core (:unit :number :amount-of-money :time :temperature :distance :volume :url :phone-number :email :timezone :ordinal :cycle :unit-of-duration :leven-unit :leven-product :quantity)}
duckling.core=> (run)
:ro$core: 251 examples, 0 failed.
#'duckling.core/c
duckling.core=>

**Comment by patapizza** [comment]
@brezuicabogdan Multumim!

**Comment by brezuicabogdan** [comment]
@patapizza No,  thank you. I love Wit and I live building bots with Wit. This is only the first step. I plan to improve ducklings for Romanian as much as I can.

**Pull request merged**
