### PR TITLE
Russian numbers new

### PR DESCRIPTION
**Pull request by petr-tik**
rebased from upstream/master and now sending a PR with russian ordinals

Also, just wondering if the develop branch is gone you should probably change  Contributing section of the documentation to tell people to send PRs against the master branch.

### CODE REVIEW

**Comment by petr-tik** [comment]
running on local machine
```bash
petr_tik@merluza:~/Coding/duckling$ git checkout russian_numbers_new 
Switched to branch 'russian_numbers_new'
petr_tik@merluza:~/Coding/duckling$ git rebase -i master 
Successfully rebased and updated refs/heads/russian_numbers_new.
petr_tik@merluza:~/Coding/duckling$ lein repl
WARNING: update already refers to: #'clojure.core/update in namespace: plumbing.core, being replaced by: #'plumbing.core/update
WARNING: update already refers to: #'clojure.core/update in namespace: duckling.core, being replaced by: #'plumbing.core/update
WARNING: update already refers to: #'clojure.core/update in namespace: duckling.corpus, being replaced by: #'plumbing.core/update
nREPL server started on port 42640 on host 127.0.0.1 - nrepl://127.0.0.1:42640
REPL-y 0.3.7, nREPL 0.2.3
Clojure 1.8.0
OpenJDK 64-Bit Server VM 1.8.0_66-internal-b17
    Docs: (doc function-name-here)
          (find-doc "part-of-name-here")
  Source: (source function-name-here)
 Javadoc: (javadoc java-object-or-class-here)
    Exit: Control+D or (exit) or (quit)
 Results: Stored in vars *1, *2, *3, an exception in *e

duckling.core=> (load!)
{:pt$core (:number :distance :volume :temperature :time :unit :amount-of-money :url :leven-unit :quantity :timezone :ordinal :unit-of-duration :phone-number :cycle :duration :email), :ru$core (:number :ordinal), :ja$core (:number :temperature :ordinal), :fr$core (:number :distance :volume :temperature :time :leven-unit :leven-product :quantity :unit :amount-of-money :url :cycle :unit-of-duration :ordinal :phone-number :duration :timezone :email), :es$core (:number :distance :volume :temperature :time :unit :amount-of-money :url :timezone :phone-number :cycle :unit-of-duration :duration :ordinal :email), :cn$core (:number :temperature :time :cycle :unit-of-duration :duration :ordinal), :ar$core (:number :ordinal), :it$core (:time :cycle :unit-of-duration :number :ordinal :duration), :kr$core (:number), :et$core (:number :ordinal), :en$core (:number :distance :volume :temperature :time :leven-unit :leven-product :unit :quantity :amount-of-money :url :ordinal :phone-number :cycle :unit-of-duration :duration :timezone :email)}
duckling.core=> (run)
:pt$core: 374 examples, 0 failed.
:ru$core: 72 examples, 0 failed.
:ja$core: 55 examples, 0 failed.
:fr$core: 417 examples, 0 failed.
:es$core: 296 examples, 0 failed.
:cn$core: 327 examples, 0 failed.
:ar$core: 31 examples, 0 failed.
:it$core: 137 examples, 0 failed.
:kr$core: 85 examples, 0 failed.
:et$core: 48 examples, 0 failed.
:en$core: 449 examples, 0 failed.
#'duckling.core/c
```

Same errors after rebasing

**Comment by petr-tik** [comment]
Hey @patapizza, I've rebased on upstream/master and it's still failing to build.

**Comment by patapizza** [comment]
Hi @petr-tik,

There are 2 errors when I run `lein test`:
```Ran 8 tests containing 26 assertions.
0 failures, 2 errors.
Tests failed.```

Do tests pass on your end?

**Comment by petr-tik** [comment]
Ran lein test on my branch (still not rebased) and not updated master
```bash
Ran 8 tests containing 30 assertions.
0 failures, 0 errors.

Switched to branch 'master'
Your branch is up-to-date with 'origin/master'.
petr_tik@merluza:~/Coding/duckling$ lein test
lein test duckling.ml.naivebayes-test
lein test duckling.time.obj-test
lein test duckling.time.pred-test
lein test duckling.util-test
Ran 8 tests containing 26 assertions.
0 failures, 2 errors.
Tests failed.
```

**Comment by l5t** [comment]
Thanks a lot for your contribution

**Pull request merged**
