### PR TITLE
Add en semaine for french version (during the week)

### PR DESCRIPTION
**Pull request by victorboissiere**
One case that wasn't handled in Duckling was "I prefer during the week" (I have multiple discussions where the user says that). I added the "en semaine" equivalent in the french version with a grain week.

### CODE REVIEW

**Comment by ar7hur** [comment]
In my opinion, "en semaine" means "from Monday to Friday", right? (like, not the weekend)
So it's different from "cette semaine".
Do you agree with my assessment?

**Comment by victorboissiere** [comment]
Yes I do. I did it because I taught a grain week will help to define directly in the specific application that uses Duckling what a week  is (monday to friday or monday to saturday for example). However, it would seems better to change it directly in duckling and specify an interval. I'll do that and change the code.

**Comment by ar7hur** [comment]
Yes, `:grain` is used internally to "resolve" dates. In that case it should definitely be `:day`, and you should use an interval.

**Comment by victorboissiere** [comment]
You're right. It seems way better that way. It just updated the code to reflect those changes. Thank you for your help

**Comment by ar7hur** [comment]
Just deployed 0.4.15 to Clojars

**Pull request merged**
