### PR TITLE
Norwegian language

### PR DESCRIPTION
**Pull request by pettersamuelsen**
Adds support for parsing of Norwegian (bokmål) time, duration, finance, numbers and cycles.

### CODE REVIEW

**Comment by magnusburton** [comment]
Alright if I use this to add Swedish as well?

**Comment by pettersamuelsen** [comment]
Sure thing. The more the merrier!

**Comment by pettersamuelsen** [comment]
@ar7hur @l5t any news on this? I'd love to use this in production.

**Comment by ar7hur** [comment]
I've seen you chose `nb` over `no` for language code. Out of curiosity what's the reason?

**Comment by ar7hur** [comment]
0.4.17 deployed to Clojars

**Comment by justinas-vd** [comment]
Most likely because 'nb' is more informative than 'no'. It is clear that he means Norwegian bokmal (the standard written Norwegian) and not Nynorsk.

**Comment by pettersamuelsen** [comment]
That is correct, @justinas-vd. `no` is the ISO code for Norwegian in general, but `nb` is the individual code for `Norwegian Bokmål` (the official Norwegian language). `nn` is the other form which would need its own parser.
Thanks for the merge!

**Pull request merged**
