### PR TITLE
Croatian(HR) language support

### PR DESCRIPTION
**Pull request by durch**
Added Croatian(HR) language support for all elements

### CODE REVIEW

**Comment by patapizza** [comment]
Thanks a lot @durch!

**Comment by durch** [comment]
My pleasure :)

**Comment by durch** [comment]
@patapizza do you have an idea when this will be deployed to duckling.wit.ai?

**Comment by patapizza** [comment]
@durch I don't have a specific ETA yet, but this is definitely on my list. Thanks for your patience.

**Comment by durch** [comment]
Thnx @patapizza, don't worry, I was just wondering :), I have a few projects lined up that would greatly benefit from duckling.

**Pull request merged**
