### PR TITLE
Arabic corpus (numbers and ordinals forms)

### PR DESCRIPTION
**Pull request by aggounix**
Adding feminine masculine arabic numbers and ordinals in corpus and rules

### CODE REVIEW

**Comment by aggounix** [comment]
Hi, I tested the project locally and I get no error
It is not cler why it failed on ci/circleci
Can I know why it failed?
here is my test result file
[duckling_test.txt](https://github.com/wit-ai/duckling/files/538770/duckling_test.txt)

**Comment by petr-tik** [comment]
Hey @aggounix,
I think it's related to #114 and I hope it gets resolved soon, so people get the satisfaction of green in their CI tests.

**Comment by aggounix** [comment]
thx, I hope it will be fixed soon :)

**Comment by ar7hur** [comment]
Yes sorry the CircleCI integration is broken, not your fault. Will fix or remove soon.

**Comment by ar7hur** [comment]
6 corpus examples are failing, could you please see what's happening?

```
duckling.core=> (load!)
"not found" "ثلاثة و ثلاثون"
"not found" "أربعة عشر"
"not found" "ستة عشر"
"not found" "سبعة عشر"
"not found" "ثمانية عشر"
"not found" "خمسمائة و خمسة و عشرون"
{:pt$core (:phone-number :number :distance :volume :temperature :time :url :email :timezone :unit :amount-of-money :leven-unit :quantity :ordinal :unit-of-duration :cycle :duration), :ko$core (:number), :id$core (:unit :number :amount-of-money :ordinal), :ru$core (:number :ordinal), :ja$core (:number :temperature :ordinal), :fr$core (:phone-number :number :time :distance :volume :temperature :url :email :timezone :unit :amount-of-money :leven-unit :leven-product :quantity :ordinal :cycle :unit-of-duration :duration), :es$core (:phone-number :number :distance :volume :temperature :time :url :email :timezone :unit :amount-of-money :cycle :unit-of-duration :duration :ordinal), :da$core (:number :time :timezone :ordinal :cycle :unit-of-duration :duration), :zh$core (:number :temperature :time :ordinal :cycle :unit-of-duration :duration), :ar$core (:number :ordinal), :ga$core (:unit :number :amount-of-money :distance :volume :temperature :time), :it$core (:number :time :ordinal :cycle :unit-of-duration :duration), :de$core (:number :time :ordinal :cycle :unit-of-duration :duration :timezone), :vi$core (:unit :number :amount-of-money), :uk$core (:number :ordinal), :et$core (:number :ordinal), :en$core (:phone-number :number :distance :volume :temperature :time :url :email :timezone :unit :amount-of-money :leven-unit :quantity :leven-product :ordinal :cycle :unit-of-duration :duration)}
duckling.core=> (run)
:pt$core: 382 examples, 0 failed.
:ko$core: 85 examples, 0 failed.
:id$core: 79 examples, 0 failed.
:ru$core: 84 examples, 0 failed.
:ja$core: 55 examples, 0 failed.
:fr$core: 502 examples, 0 failed.
:es$core: 295 examples, 0 failed.
:da$core: 354 examples, 0 failed.
:zh$core: 329 examples, 0 failed.
0 FAIL "ثلاثة و ثلاثون"
    Expected 33
    Got      3
    Got      30
1 FAIL "أربعة عشر"
    Expected 14
    Got      4
    Got      10
2 FAIL "ستة عشر"
    Expected 16
    Got      6
    Got      10
3 FAIL "سبعة عشر"
    Expected 17
    Got      7
    Got      10
4 FAIL "ثمانية عشر"
    Expected 18
    Got      8
    Got      10
5 FAIL "خمسمائة و خمسة و عشرون"
    Expected 525
    Got      20
    Got      505
    Got      505
:ar$core: 33 examples, 6 failed.
```

**Comment by aggounix** [comment]
Hi, thank you
For the fails, I think because rules put at original file are confusing for numbers  from 11 to 20 because the code is trying to convert every word in the numbers first and not as a whole
I can try to modify the rules until it passes if you want

**Comment by l5t** [comment]
@aggounix tested and still 2 failed examples
"not found" "إحدى عشرة"
"not found" "إثنتى عشر"

**Pull request merged**
